@Web_API_HostAddress = http://localhost:5095

GET {{Web_API_HostAddress}}/weatherforecast/
Accept: application/json

###
# New GET for new endpoint
GET {{Web_API_HostAddress}}/pizza/
Accept: application/json

###
POST {{Web_API_HostAddress}}/pizza/
Content-Type: application/json-patch+json

{
    "name": "Hawaii",
    "isGlutenFree": false,
    "price": 11.31
    
}

###
PUT {{Web_API_HostAddress}}/pizza/3
Content-Type: application/json-patch+json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false,
    "price": 13.11
}

###
GET {{Web_API_HostAddress}}/pizza/3
Accept: application/json

###
DELETE {{Web_API_HostAddress}}/pizza/3

###
GET {{Web_API_HostAddress}}/pizza/
Accept: application/json

###